default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-petmate_development

test:
  <<: *default
  database: rails-petmate_test

production:
  <<: *default
  database: rails-petmate_production
