default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development

test:
  <<: *default
  database: rails-watch-list_test

production:
  <<: *default
  database: petmate_production
  username: petmate
  password: <%= ENV["PETMATE_DATABASE_PASSWORD"] %>
